### ISSUE TITLE
errors after following ReadMe

### ISSUE THREAD

**Issue by lewislepton** [RblSb/KhaHotReload#5]
yo,

I followed the instructions, but I seem to get nothing but errors asking about a server. I even copied what I needed from the `tasks.json` & `launch.json`, but still errors.
the library is in the right folder as well

this is what pops up right away after the setup
```
> Executing task: node /usr/local/lib/kha/make debug-html5 --watch <

Using Kha (00520ec1, M Kinc, M Tools/khamake) from /usr/local/lib/kha
Creating Kha project.
(node:2348) UnhandledPromiseRejectionWarning: Error: Cannot find module '/Users/lepton/Developer/Kha/GAMES/OTO/server/bin/server.js'
Require stack:
- /usr/local/lib/kha/Tools/khamake/out/ProjectFile.js
- /usr/local/lib/kha/Tools/khamake/out/main.js
- /usr/local/lib/kha/Tools/khamake/out/khamake.js
- /usr/local/lib/kha/Tools/khamake/khamake.js
- /usr/local/lib/kha/make.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at eval (eval at <anonymous> (/usr/local/lib/kha/Tools/khamake/out/ProjectFile.js:52:17), <anonymous>:20:17)
    at /usr/local/lib/kha/Tools/khamake/out/ProjectFile.js:52:144
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2348) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: khafile.js did not call resolve, no project created.

Terminal will be reused by tasks, press any key to close it.
```

so it bitches about the server & seems to be pointing not in the Library path, so I changed it so it goes right to `server.js` & this is the next error

```
> Executing task: node /usr/local/lib/kha/make debug-html5 --watch <

Using Kha (00520ec1, M Kinc, M Tools/khamake) from /usr/local/lib/kha
Creating Kha project.
(node:2385) UnhandledPromiseRejectionWarning: TypeError: Server is not a constructor
    at eval (eval at <anonymous> (/usr/local/lib/kha/Tools/khamake/out/ProjectFile.js:52:17), <anonymous>:22:17)
    at /usr/local/lib/kha/Tools/khamake/out/ProjectFile.js:52:144
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2385) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2385) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: khafile.js did not call resolve, no project created.

Terminal will be reused by tasks, press any key to close it.
```

& that's just a bit weird & don't know where to go next to fix it. I also saw about your black screen problem, so will get V6 once I figure out this problem first
I am using my own engine. but obviously still have the `Main.hx` with `main()` to put in the client stuff. but wondered if that's a problem. but seems a bit unlikely.

anyhow. hope you can help or shine some light on this

xxx

**Comment by lewislepton** [comment]
oh I forgot to add. it also pops up with this right after it doesn't work

![Screenshot 2020-05-19 at 18 56 07](https://user-images.githubusercontent.com/11299322/82361227-79112400-9a02-11ea-9c0e-517fb1514bc0.png)

**Comment by RblSb** [comment]
Hi! Does it works for you if you clone repo and run in VSCode with `HTML5-watch` launch? Also, try to change `kha.khaPath` (maybe it is wrong?)

**Comment by lewislepton** [comment]
I mean, with the example it works fine. black screen, much like the other issue #2 
![Screenshot 2020-05-20 at 00 39 01](https://user-images.githubusercontent.com/11299322/82388988-d91fbe80-9a32-11ea-9982-a42e988047bf.png)

once I try it in my own thing. exact same way, its not working. no black screen, just the errors like before in the terminal box thing

which `kha.khaPath` are you talking about. the settings/preferences or where, not sure what you mean the path to change since I know mainly the preferences one

x

**Comment by lewislepton** [comment]
it worked fine in the regular html5 - same with the given example of this repo. shapes popped up. but no reload

**Comment by lewislepton** [comment]
I guess this is something found first of all where the `Server` seems to be pointing to nowhere the `server.js`

```
if (!libPath) libPath = path.resolve('./Libraries/hotml');
const Server = require(path.resolve('./server/bin/server.js')).Main; // this seems wrong, was changed & still didn't work. but it seems wrong
```

**Comment by lewislepton** [comment]
but just to ask. is there any extra libraries need installing? found `hxnodejs` & `utest` when looking in the `build.hxml`. only asking since there was no mention of them in the repo readme

**Comment by RblSb** [comment]
Sorry for this, i forgot to update one line in readme after lib update. See latest commit.
`kha.khaPath` is VSCode settings (also KodeStudio i think). Also, for fixing black screen, update electron binary as described in #2.

**Comment by RblSb** [comment]
Feel free to reopen

**Comment by lewislepton** [comment]
cool spot. cheers man. ill reopen if need be

thanks again

**Comment by lewislepton** [comment]
with updating the electron version. how that that be done. I tried plopping in the executable, couldn't get it to work. tried installing other ways, but nope. is this an install that can be done from vscode, or is it just a simple drag & drop?

thanks again

**Comment by RblSb** [comment]
Sorry, forgot to answer. Simple drag & drop, for me electron binaries is inside:
`HOME/.vscode/extensions/kodetech.electron-debug-18.11.1/.electron/4.0.1`

**Comment by lewislepton** [comment]
hey bud,

sorry Im just not getting the result. swapped electron versions, nothing works. just pops up with error messages if trying something. it says about the launch.json most of the time. even if its been swapped. just cant think what it could be wrong

thanks again

![Screenshot 2020-06-15 at 18 44 06](https://user-images.githubusercontent.com/11299322/84689757-5870b700-af39-11ea-87f5-8935cc3e8404.png)

![Screenshot 2020-06-15 at 18 46 52](https://user-images.githubusercontent.com/11299322/84689769-5c9cd480-af39-11ea-8490-4aff0a922151.png)

<img width="658" alt="Screenshot 2020-06-15 at 18 44 12" src="https://user-images.githubusercontent.com/11299322/84689760-59a1e400-af39-11ea-9834-5ee577429af2.png">

**Comment by RblSb** [comment]
Try to press cmd-s (save file) on source file after you run html5 watch build, maybe this is related to timeout bug when task doesn't know that compilation is complete.

**Comment by lewislepton** [comment]
AHA, for some reason, it worked with 4.0.1 electron. oddly. could not say why.
but did try a sway with electron to 9.whatever. seems to work completely fine. it is slow, but that also may just be my machine.
but ill message on here if there are troubles. but I really don't know why this is now working

**Comment by lewislepton** [comment]
thanks again though. big help xxx
